# Header
menu:
  Home: /
  Archives: /archives

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://placehold.it/1300x500"

# Social Accounts
twitter_url:
facebook_url: 
behance_url: 
googleplus_url: 
dribble_url:
rss_url:
github_url: 