# Header
menu:
  首页: /
  文章目录: /archives

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://placehold.it/1300x500"

# Social Accounts
twitter_url: "http://twitter.com"
facebook_url: "http://facebook.com"
behance_url: "http://facebook.com"
dribble_url: "http://facebook.com"
rss_url: "http://facebook.com"
googleplus_url: "http://google.com"